# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Init submodule
      run: git submodule init
    - name: Add submodule
      run: git submodule update --recursive --remote --force
    - name: Publish
      run: dotnet publish AutoUpdater/AutoUpdater.csproj -o build\ -c Release -p:PublishTrimmed=true -p:PublishSingleFile=true -p:SelfContained=true -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        tag_name: generated_release_${{ github.run_id }}-${{ github.run_attempt }}
        name: Generated release
        body: This release was generated by Github Actions. It may or may not be stable.
        files: build/AutoUpdater.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
